### ISSUE TITLE
Identify five essential data flows (source-transformations-sink) through the software. Develop use-cases diagrams related to these data flows.

### ISSUE THREAD

**Issue by caseyschmitz** [caseyschmitz/CYBR8420-GotRoot#23]

**Comment by caseyschmitz** [comment]
Essential data flows identified to include:

1. Management of the Master Password
2. Management of the Key Encryption Key
3. Management of Secrets
4. Management of Passwords associated with website/application credentials.
5. Management of the Sharing of Secrets

**Comment by caseyschmitz** [comment]
@sdfrench created Skeleton for SSE document #17

**Comment by caseyschmitz** [comment]
Diagrams moved to draw.io to improve workflow.

**Comment by caseyschmitz** [comment]
@sdfrench taking the lead as "Diagram Steward" - will manage major commits to diagrams moving forward.

**Comment by Guerrias** [comment]
Scott,
I submitted some modifier the diagrams since the include arrows were in the wrong direction and we missed the links between main uses cases and the misuse use cases that threaten them.

Sent from Yahoo Mail for iPhone


On Wednesday, October 2, 2019, 9:31 PM, caseyschmitz <notifications@github.com> wrote:


@sdfrench taking the lead as "Diagram Steward" - will manage major commits to diagrams moving forward.
